### PR TITLE
Feature/upgrade dependencies

### PR DESCRIPTION
**Pull request by ricardojmendez**
Upgraded dependencies and  added test profiles.

### CODE REVIEW

**Comment by ricardojmendez** [comment]
Goldfish memory - I'd forgotten that, as discussed on #14, Urly is not under active development.

**Comment by ricardojmendez** [comment]
Wouldn't mind adopting the library, for what it's worth. I don't expect I'll do any massive changes, but think there's value in having it out there.

**Comment by michaelklishin** [comment]
@ricardojmendez I've added you as a collaborator. Thank you for stepping in. I wouldn't mind more radical changes to the library as long as the version is updated accordingly and the changes make sense :)

**Comment by ricardojmendez** [comment]
Perfect, thanks!  I intend to just keep it up to date, but I'll keep you posted on any potential breaking changes so we don't trip anyone.

I'm [ricardojmendez](https://clojars.org/ricardojmendez) on Clojars. If you can give me access to push, that'd make it easier to just build releases.

Cheers!

**Pull request merged**
